- README.md
> fixed the map component example link

- examples/renderer/renderer.html
- examples/renderer/renderer.js
- src/component/FeatureRenderer.js
- test/load-tests.js
- test/spec/GeoExt/component/FeatureRenderer.test.js
This is now ready for review @marcjansen @chrismayer et al.
> Add feature renderer

- resources/css/gx-popup.css
- src/panel/Popup.js
- test/load-tests.js
- test/spec/GeoExt/panel/Popup.test.js
This PR suggest some small changes to the Popup class:
* Use ext methods when creating the wrapper dom,
* named methdos as eventlisteners
* destroy logic
* CSS enhancements (clickabla area now bigger)
* very basic tests
/cc @chrismayer
> Popup enhancements

- src/data/TreeStore.js
Due to a change in Ext JS we have to restructure the onLayerCollectionChange
method to do what we want.
> Changes the onLayerCollectionChange behaviour

- test/spec/GeoExt/data/TreeStore.test.js
This adds some tests for the GeoExt.data.TreeStore.
> Adds some TreeStore tests

- src/component/FeatureRenderer.js
- src/data/model/Feature.js
- src/data/model/LayerTreeNode.js
- src/data/store/Features.js
- src/grid/column/Symbolizer.js
Title says it all. Please review.
> Add missing license header

- src/data/store/Features.js
- test/spec/GeoExt/data/store/Features.test.js
This PR suggests some minor changes to the feature store and associated tests.
See the individual commit messages for the changes.
Please review.
> Minor changes to the feature store

- .sencha/package/Boot.js
- .sencha/package/Microloader.js
- .sencha/package/codegen.json
- .sencha/package/init-impl.xml
- .sencha/package/sass-impl.xml
- .sencha/package/sencha.cfg
- .sencha/package/slice-impl.xml
- .sencha/package/sub-builds.xml
- examples/component/map.html
- examples/component/overviewMap.html
- examples/features/grid.html
- examples/mapviewform/mapviewform.html
- examples/popup/gx-popup.html
- examples/print/basic-mapfish.html
- examples/renderer/renderer.html
- examples/tree/panel.html
- examples/tree/tree-legend-simple.html
- sass/example/fashion.html
- sass/example/render.js
- sass/example/theme.html
- src/panel/Popup.js
- test/index.html
also changed the online resources to cloudflares CDN as i didnt find "official" one.
> Upgrading ExtJS to latest version 6.0.0.640 GPL

- test/spec/GeoExt/component/Map.test.js
> Add a testcase to verify map rerendering

- .eslintrc
- package.json
- test/.eslintrc
… and fix eslint rule config / remove one rule that never worked.
> Update the modules we depend upon

- src/data/model/LayerTreeNode.js
- src/data/store/Tree.js
- test/spec/GeoExt/data/store/Tree.test.js
Two available modes
'classic':
- Check a leaf --> all parent nodes are checked
- Uncheck all leafs in a folder --> parent node is unchecked
- Check a folder Node --> all children are checked
- Uncheck a folder Node --> all children are unchecked
'ol3':
- Emulates the behaviour of an ol.layer.Group, so a parentfolder can be unchecked but still contain checked leafs and vice versa.
> Introduces a control for the treenode/parentnode check behaviour

- src/data/serializer/XYZ.js
- test/load-tests.js
- test/spec/GeoExt/data/serializer/XYZ.test.js
Just another print serializer for ol.source.XYZ
> Add a print-serializer for ol.source.XYZ

- test/load-tests.js
This should have been a part of #70. 
Please review.
> Don't try to load non-existing test-file

- src/component/Popup.js
- src/data/MapfishPrintProvider.js
- src/data/model/Base.js
- src/data/model/Feature.js
- src/data/model/Layer.js
- src/data/model/LayerTreeNode.js
- src/data/model/Object.js
- src/data/model/print/Capability.js
- src/data/model/print/Layout.js
- src/data/model/print/LayoutAttributes.js
- src/data/serializer/Base.js
- src/data/serializer/ImageWMS.js
- src/data/serializer/TileWMS.js
- src/data/serializer/Vector.js
- src/data/serializer/WMTS.js
- src/data/serializer/XYZ.js
- src/data/store/Collection.js
- src/data/store/Features.js
- src/data/store/Tree.js
- src/grid/column/Symbolizer.js
- src/tree/Panel.js
This PR suggests to add `@class` docs to all classes. Additionally two already existing (but wrong) `@class` docs are changed.
Please review.
> More consistent @class docs

- ci/update-gh-pages.sh
- docresources/eg-iframe.html
- src/component/Map.js
- src/component/OverviewMap.js
- src/component/Popup.js
Runable examples in jsduck documentation.
> Runable examples in jsduck documentation

- index.html
> Fix link to docs-w-ext

- ci/update-gh-pages.sh
merging, no functional change.
> Reference eg-iframe.html from $TRAVIS_BUILD_DIR

- src/component/Map.js
- src/component/OverviewMap.js
- src/component/Popup.js
No formal review, as this is just API-docs formatting
> Ensure line-length of 80 chars maximum

- docresources/eg-iframe.html
Title says it all. Merging without formal review, this just affects the documentation.
> Correct the path to GeoExt src folder

- test/spec/GeoExt/data/serializer/Vector.test.js
> Expect the default ol3 color for texts in test

- ci/update-gh-pages.sh
> We don't generate CSS, remove cp line

- package.json
- test/index.html
> Upgrade & clean-up test dependencies to fix encoding errors on travis

- .travis.yml
- package.json
This is mostly a stylistic change, but moving the linting in the `pretest`-phase makes alot of sense to me.
Please review.
> Run eslint prior to testing

- src/component/FeatureRenderer.js
- src/component/Map.js
- src/component/OverviewMap.js
- src/component/Popup.js
- src/data/MapfishPrintProvider.js
- src/data/model/Base.js
- src/data/model/Feature.js
- src/data/model/Layer.js
- src/data/model/LayerTreeNode.js
- src/data/model/OlObject.js
- src/data/model/print/Capability.js
- src/data/model/print/Layout.js
- src/data/model/print/LayoutAttribute.js
- src/data/serializer/Base.js
- src/data/serializer/ImageWMS.js
- src/data/serializer/TileWMS.js
- src/data/serializer/Vector.js
- src/data/serializer/WMTS.js
- src/data/serializer/XYZ.js
- src/data/store/Features.js
- src/data/store/Layers.js
- src/data/store/LayersTree.js
- src/data/store/OlObjects.js
- src/grid/column/Symbolizer.js
- src/mixin/SymbolCheck.js
- src/util/Layer.js
> Change the copyright year to include 2016

- package.json
Karma version update to 0.13.20 to fix problem: https://github.com/karma-runner/karma/pull/1884
> Karma version update

- package.json
> Patch updates for dependencies

- package.json
This PR suggests to use a more recent version of `eslint`.
Please review.
> Update to new major version of eslint

- README.md
Just a little gimmick to show of the status of NPM dependencies. The service is free for public repositories and doesn't need any permissions from us.
> Add dependency status badges to README.md

- COMMERCIAL-LICENCE.md
- LICENSE
- LICENSE-FAQ.md
Add a note about dual licensing. Still missing the LICENSE-FAQ.md
> Fix #154 - Add note on dual license

- COMMERCIAL-LICENCE.md
- LICENSE
> Harmonize terms in licence texts

- universal-app.md
Hi,
I've updated the universal app documentation.
Regards from Bonn!
> Universal app documentation updated

- LICENSE-FAQ.md
This PR suggests to add screenshots of my communication with Sencha to have a rationale behind #154 and #155 inside of the repo. The screenies are anonymized, so as to not leak the contact address.
Please review (and please double check if I didn't leak personal information)
> More prose for explanation of licenses

- test/spec/GeoExt/data/store/Layers.test.js
Adding more tests for the ``GeoExt.data.store.Layers`` class.
> Add more tests for LayerStore

- ci/update-gh-pages.sh
This may be the culprit preventing the update of the gh-pages branch.
> Fix line break in multiline shell command

- src/component/FeatureRenderer.js
- src/component/Map.js
- src/component/OverviewMap.js
- src/component/Popup.js
- src/data/MapfishPrintProvider.js
- src/data/model/Base.js
- src/data/model/Feature.js
- src/data/model/Layer.js
- src/data/model/LayerTreeNode.js
- src/data/model/OlObject.js
- src/data/model/print/Capability.js
- src/data/model/print/Layout.js
- src/data/model/print/LayoutAttribute.js
- src/data/serializer/Base.js
- src/data/serializer/ImageWMS.js
- src/data/serializer/TileWMS.js
- src/data/serializer/Vector.js
- src/data/serializer/WMTS.js
- src/data/serializer/XYZ.js
- src/data/store/Features.js
- src/data/store/Layers.js
- src/data/store/LayersTree.js
- src/data/store/OlObjects.js
- src/mixin/SymbolCheck.js
- src/util/Layer.js
I don't think this needs a formal review.
> Update year in copyright header

- src/component/FeatureRenderer.js
This is just a cosmetic change to bring this source file more in sync with most of the other in the library.
Please review.
> Use me alias in feature renderer

- README.md
- bin/example-generator/example.html.tpl
- docresources/eg-iframe.html
- examples/component/map.html
- examples/component/overviewMap.js
- examples/features/grid.js
- examples/print/basic-mapfish.js
- examples/tree/panel.js
- examples/tree/tree-legend-simple.js
- test/karma.conf.js
- universal-app.md
This changes the readme to hint more clearly how we suggest to use the library.
Here is the new readme: https://github.com/marcjansen/geoext3/blob/2a3efbf6d58b0e3e35f73d2110f940da9490117b/README.md
> Adjust usage instructions

- README.md
> Fix the dependency status badges

- index.html
Title says it all...
See also: https://github.com/openlayers/openlayers/releases/tag/v4.2.0
> Update current OL version in version overview

- package.json
- src/component/OverviewMap.js
- src/data/MapfishPrintProvider.js
- src/data/serializer/Vector.js
- src/data/serializer/XYZ.js
- test/spec/GeoExt/component/Map.test.js
- test/spec/GeoExt/component/OverviewMap.test.js
- test/spec/GeoExt/data/MapfishPrintProvider.test.js
- test/spec/GeoExt/data/model/OlObject.test.js
- test/spec/GeoExt/data/serializer/Vector.test.js
> chore(package): update eslint to version 4.3.0

- package.json
> chore(package): update sinon to version 4.0.0

- package.json
> chore(package): update openlayers to version 4.4.1

- package.json
> chore(package): update sinon to version 4.1.0

- package.json
> chore(package): update browser-sync to version 2.21.0

- package.json
> chore(package): update browser-sync to version 2.23.5

- package.json
> Revert "Update mocha to the latest version 🚀"

- package.json
> chore(package): update browser-sync to version 2.24.6

- src/data/MapfishPrintProvider.js
Adds error handling if the capabilities json can not be loaded.
@weskamm @KaiVolland Please review.
> Add print provider error handling

- package.json
> chore(package): update browser-sync to version 2.26.3

- package.json
> chore(package): update karma to version 3.1.1

- package.json
> chore(package): update karma to version 3.1.4

- examples/print/basic-mapfish.js
- test/spec/GeoExt/data/MapfishPrintProvider.test.js
> Fixes print test urls

- .gitignore
- package.json
Note that the tests currently fail, fixed in #461 .
> Updates a couple of dependencies

- README.md
> Link to examples on gh-pages

- package.json
> chore(package): update eslint to version 5.14.1

- docresources/eg-iframe.html
- universal-app.md
Use local OpenLayers for API-doc examples and reference v4.6.5 in universal app tutorial.
Please review.
> Harmonize usage of OpenLayers

- package.json
> chore(package): update sinon to version 7.3.1

- examples/features/grid-filter.js
> Adding missing require for grid-filter example

- src/util/OGCFilter.js
- test/spec/GeoExt/util/OGCFilter.test.js
Extracted code generating OGC filter body content from given ExtJS filter to own method to enhance readability and reusability.
Please review @marcjansen @dnlkoch
> OgcFilter util refactoring

- examples/renderer/renderer.js
- package.json
> chore(package): update eslint to version 6.0.1

- development.md
Fix a script name and note they can be found in package.json
> Minor changes to development.md

- index.html
Add in 5 new examples, and reorder examples (slightly) to group by category
> Add new examples to docs page

- package.json
> chore(package): update karma-coverage to version 2.0.1

- package.json
> chore(package): update eslint to version 6.2.2

- examples/features/grid-filter.js
- src/data/store/OlObjects.js
- src/util/OGCFilter.js
- test/spec/GeoExt/util/OGCFilter.test.js
This adds a check to avoid duplicates in the ol.Collection.
@marcjansen @weskamm please review
> Adds check to avoid duplicates

- src/data/MapfishPrintProvider.js
- src/data/serializer/Vector.js
> Use map extent when getting vector features for print

- README.md
> Add OSGeo logo to README

- src/util/OGCFilter.js
> Add filter operators

- CONTRIBUTING.md
Add example command for running the test suite in a browser
> Add example of running tests in browser

- bin/fetch-external-resources.js
- bin/progress.js
- bin/util.js
This PR suggests to better group utility functions by intent.
Also the progress bar looks less ASCII-esque.
Please review.
> Better code splitting in util script

- src/data/serializer/ImageWMS.js
Fixes the determination of style names when printing.
> Fix style handling

- classic/form/field/GeocoderComboBox.js
- test/spec/GeoExt/form/field/GeocoderComboBox.test.js
"Search for a location" preferable to 'Search a location'.
> Update GeocoderComboBox text

- src/data/serializer/TileWMS.js
Same fix as #650 
Please review.
> Fix style handling for TileWMS layers

- src/data/MapfishPrintProvider.js
Add config flag to be able to use standard ajax requests instead of jsonp.
Please review.
> Add jsonp config flag

- test/spec/GeoExt/util/OGCFilter.test.js
This makes the the `OGCFilter` test better readable IMO.
Please review, this might be my single understanding that it is easier to comprehend now than before.
> Remove duplication in tests

- package-lock.json
- package.json
This updates several dependencies to their latest version (no SemVer major change).
Also the changes to the lockfile resulting from `npm audit fix` are included.
Please review.
> More dependency updates

- src/data/model/LayerTreeNode.js
> Fix check for classic mode

- CONTRIBUTING.md
- README.md
- package.json
- universal-app.md
rename all links to the github repository and the github pages
> Rename links to github repository and github pages

- classic/selection/FeatureCheckboxModel.js
- classic/selection/FeatureModelMixin.js
- classic/selection/FeatureRowModel.js
- examples/features/grid-map-selection.html
- examples/features/grid-map-selection.js
- test/index.html
- test/spec/GeoExt/selection/FeatureRowModel.test.js
added checkbox selection model.
Fixes  #636
> feature selection model as a mixin

- src/data/model/Layer.js
- src/data/store/Layers.js
- test/spec/GeoExt/data/store/Layers.test.js
Fixes: https://github.com/geoext/geoext/issues/489
> Synchronize properties of the layer.

- src/data/store/WfsFeatures.js
This PR introduces debouncing instead of request aborting.
In general it seems better to solve the problem of many successive requests by not triggering many in the first place. As request aborting is not always working as expected, and sometimes is not possible, the debouncing approach will work more reliable.
Fixes https://github.com/compassinformatics/cpsi-mapview/issues/422
> Use debouncing instead of aborting.

- .github/workflows/on-push-master.yml
- CHANGELOG.md
- README.md
- examples/component/map.html
- examples/component/overviewMap.html
- examples/component/overviewMap.js
- examples/features/grid-filter.html
- examples/features/grid-map-selection.html
- examples/features/grid-paging.html
- examples/features/grid-spatial-filter.html
- examples/features/grid.html
- examples/filtered-heatmap/filtered-heatmap.html
- examples/geocoder/geocoder-combo.html
- examples/mapviewform/mapviewform.html
- examples/modern-layerlist/modern-layerlist.html
- examples/modern-layerlist/modern-layerlist.js
- examples/modern-map/modern-map.html
- examples/modern-map/modern-map.js
- examples/popup/gx-popup.html
- examples/print/basic-mapfish.html
- examples/renderer/renderer.html
- examples/state/stateful-map.html
- examples/tree/panel.html
- examples/tree/tree-legend-simple.html
- package-lock.json
- package.json
- src/data/store/Features.js
- test/karma.conf.js
This PR replaces @geoext/openlayers-legacy 6.15.1 with ol 7.1.0.
Code is adapted correspondigly.
> Updates openlayers to v7

- package-lock.json
- package.json
The title says it all, please review.
> Dependency updates and audit

- src/data/model/ArcGISRestServiceLayer.js
- src/data/store/ArcGISRestServiceLayer.js
- for description see https://github.com/compassinformatics/cpsi-mapview/pull/626
- ( follow up of https://github.com/geoext/geoext/pull/717 )
> Add Model for ArcGISRest
