geoext/geoext

src/component/Map.js, src/component/OverviewMap.js, src/tree/Panel.js
The alias is said to be faster (even though we'll hardly recognize it) and also
can be used in more places than for just components.
See e.g. http://stackoverflow.com/a/27470948/860988
Additionally more aliases are added to the classes, this was the outcome of internal discussions at the codesprint.
=> Use alias in favor of xtype

LICENSE, package.json, src/component/Map.js, src/component/OverviewMap.js, src/data/LayerStore.js, src/data/MapfishPrintProvider.js, src/data/TreeStore.js, src/data/model/Base.js, src/data/model/Object.js, src/data/model/layer/Base.js, src/data/model/layer/Group.js, src/data/model/layer/Layer.js, src/data/model/print/Capability.js, src/data/model/print/Layout.js, src/data/model/print/LayoutAttributes.js, src/data/store/Collection.js, src/panel/Popup.js, src/tree/Panel.js
Since GeoExt is based upon the GPL variant of ExtJS, GeoExt must be licensed as GPL software.
Previous releases of ExtJS permitted a different compatible OpenSource license as per their [Exception for Development](http://ee-origin.sencha.com/legal/open-source-faq/open-source-license-exception-for-development/), ([version from 2014-11-14 in the internet archive](http://web.archive.org/web/20141119170447/https://www.sencha.com/legal/open-source-faq/open-source-license-exception-for-development/)). This exception no longer exists, and sencha officials confirmed this in email conversation:
> From: &lt;name and email withheld&gt;
> Date: 18 juni 2015 21:27:00 CEST
> To: Bart van den Eijnden &lt;…&gt;
> Cc: &lt;name and email withheld&gt;
> Subject: Licensing question
>
> Bart, we no longer …
=> Switch to GPL v3.0 license

src/component/Map.js, src/component/OverviewMap.js, src/data/MapfishPrintProvider.js, src/data/TreeStore.js, src/data/model/Object.js, src/panel/Popup.js
Still, jsduck complaints about missing Classes where Ext classes are
referenced. Also, overriden properties (e.g. proxy, fields) cause
erroneous output about duplicate properties.
No config file has been provided yet. Just run `jsduck` in the project folder.
=> Fix minor issues with source code comments

examples/mapviewform/mapviewform.html, examples/mapviewform/mapviewform.js, src/data/model/Object.js
Ext allows setting model properties via property maps which wasn't working with the ol.Object wrapper.
Also, I added an example that shows how one may interact with the class.
=> Small improvements to GeoExt.data.model.Object

examples/popup/gx-popup.html, examples/popup/gx-popup.js, src/component/Map.js
This PR suggest adding two new events to `GeoExt.component.Map`:  `pointerrest` and `pointerrestout`:
With these events it easy to create nice hovering effects, that do not fire as often as the raw pointermove does.
The Popup example has been changed to now work with these new events.
Additionally some API docs were added to certain Map-properties.
Please review.
=> Add pointerrest and pointerrestout events to map component

examples/tree/panel.js, src/data/TreeStore.js
* TreeStore can be configured to show/hide the root GroupLayer Node (fixes #19)
* TreeStore reacts on adding/removing layers to the map or any ol.layer.Group within it
Still missing:
- (Better) tests for the treestore
- Map/ol.Collection should react correctly on removing nodes from the tree
@bentrm Maybe you can have a look at the second point
=> Some enhancements for the tree

examples/features/grid.html, examples/features/grid.js, src/data/model/Feature.js, src/data/store/Features.js, test/load-tests.js, test/spec/GeoExt/data/model/Feature.test.js, test/spec/GeoExt/data/store/Features.test.js
This introduces a simple FeatureStore class (incl. the FeatureModel) in order to bind OpenLayers feature objects to the data management of ExtJS.
This also provides an example showing the different ways to create a grid with a FeatureStore as data container.
=>  Implement FeatureStore and FeatureModel classes

src/data/TreeStore.js, test/spec/GeoExt/data/TreeStore.test.js
- When adding a layer to the map the state of showLayerGroupNode will be
respected on rebuilding the treestore.
- Added the related test.
=> Changes store behaviour when adding layer to map

src/data/MapfishPrintProvider.js
* getSerializedLayers supports different input formats:
* GeoExt.data.LayerStore
* ol.Collection[ol.layer.Base]
* Array[ol.layer.Base]
* Add support for ol.source.ImageWMS
=> PrintProvider getSerializedLayers() Enhancements

src/data/TreeStore.js
'name' property of an ol.layer.Group now used as display name in tree for folder
=> allowing layergroups / folders to display their name in tree

src/component/FeatureRenderer.js, src/component/Map.js, test/index.html
This PR fixes the current 3 failing tests which appeared due to changes in ol3.
The 'fitExtent' method has been renamed to 'fit'.
Master should pass all tests again now.
=> fixing the current failing tests

examples/tree/panel.js, examples/tree/tree-legend-simple.js, src/component/Map.js, src/data/MapfishPrintProvider.js, src/data/store/Layer.js, src/data/store/Tree.js, src/tree/Panel.js, test/spec/GeoExt/data/LayerStore.test.js, test/spec/GeoExt/data/TreeStore.test.js
This harmonizes the naming of the data package. Therefore this PR renames ``GeoExt.data.TreeStore`` to ``GeoExt.data.store.Tree`` and ``GeoExt.data.LayerStore`` to ``GeoExt.data.store.Layer``.
The old names are preserved as 'alternateClassName' to have a kind of backwards compatibility.
=> Harmonize store naming in data package

src/data/store/Tree.js, test/spec/GeoExt/data/TreeStore.test.js
Ok, this PR needs a little explanation:
I reversed the order the layers get added in the treestore.
The background is the following: The ol3-layer-collection contains the layers in the order they have been added.
If you add a layer at runtime to the map, it will get appended to the end of the collection / array.
In order to show this newly added layer on top in a layertree, you will need to reverse the collection.
I solved this by using 'Ext.each' with the 'reverse' flag set to true, so the code does the same as before but just in the reversed order.
This way the layertree shows the first / oldest added layers at the bottom, the newly or later added laters get shown on top.
Have a look at the layertree example to see the current problem: …
=> reversing the way we add layers in treestore

src/data/MapfishPrintProvider.js, test/spec/GeoExt/data/MapfishPrintProvider.test.js
Before this PR trying to print a map which contains an ol.layer.Group will break the code.
With this PR, ol.layer.Groups get respected in the getSerializedLayers method by extracting their layers recursively and removing the groups from the final array. The order of layers should still be in order in the final print.
=> added support for ol.layer.Group in MapfishPrintPovider

examples/features/grid.js, src/grid/column/Symbolizer.js, test/load-tests.js, test/spec/GeoExt/grid/column/Symbolizer.test.js
This adds a class providing a SymbolizerColumn in order to visualize the map style of vector features in a grid column.
The example for FeatureGrids is adapted to show such SymbolizerColumns.
Basic tests are also added with by this PR.
=> Introduce a SymbolizerColumn class

src/data/store/Features.js, test/spec/GeoExt/data/store/Features.test.js
This PR does two major things (both related to the ``GeoExt.data.store.Features`` class):
- Add a new function ``getByFeature``, which returns the corresponding record for the given feature
- Bind the store to the ``addfeature`` and ``removefeature`` events of the (possibly) underlying OpenLayers vector layer
Tests are also included. 
Please Review.
=> FeatureStore enhancements

package.json, test/.eslintrc, test/load-tests.js
This doesn't change the functionality, but helps editors (namely atom)
pick up the specific 0eslint configuration when editing files in the
test folder.
=> Move eslint config for tests to test/ folder

examples/print/basic-mapfish.js
This adds another require so that the layer in the print example can be serialized. This should have been part #47.
Please review.
Fixes #52.
=> Add missing require for serializer

examples/data/SanFranciscoPublicSchools-Points.kml, examples/print/basic-mapfish.html, examples/print/basic-mapfish.js, src/data/MapfishPrintProvider.js, src/data/serializer/Base.js, src/data/serializer/Vector.js, test/load-tests.js, test/spec/GeoExt/data/MapfishPrintProvider.test.js, test/spec/GeoExt/data/serializer/ImageWMS.test.js, test/spec/GeoExt/data/serializer/TileWMS.test.js, test/spec/GeoExt/data/serializer/Vector.test.js
This PR adds support for printing vector layers by introducing a new serializer for vectors.
What is included:
* The print example now shows a vector layer (Schools in San Franscisco from a KML file, see http://data.sfgov.org)
* The signature of `MapfishPrintProvider.getSerializedLayers` is changed from `function(layers)` to `function(mapComponent, filterFn, filterScope){`
* One now needs to pass the mapComponent isntead of the layer store, so we have a chance of getting the view resolution
* the layers to be serialized can be filterd with the two new optional arguments for a function and the scope the function is being called on
* A new serializer class
* The main class `GeoExt.data.serializer.Vector` is **heavily** inspired by the great implementation in camptocamp/ngeo (specifically …
=> Add support for printing vector layers

src/data/serializer/WMTS.js, test/load-tests.js, test/spec/GeoExt/data/serializer/WMTS.test.js
Added a serializer for ol.source.WMTS in order to print it with mapfish print servlet v3.
Credits for most parts go to camptocamp/ngeo (specifically the file src/services/print.js @ camptocamp/ngeo@3dc2a63)
=> Add a print-serializer for ol.source.WMTS

src/component/Map.js
With these changes, the mapcomponent can be used and instanciated
in an universal app, which means it can be used with both toolkits
(classic and modern or ext and touch).
Both toolkits share the constructor method which should be preferred
if possible. The initComponent method will only be available in the
classic toolkit, while the initialize method is only available in
the modern toolkit...
=> Change GeoExt.component.Map initialisation to constructor method

src/component/FeatureRenderer.js, src/component/Map.js, src/component/OverviewMap.js, src/data/MapfishPrintProvider.js, src/data/model/Layer.js, src/data/model/LayerTreeNode.js, src/data/model/Object.js, src/data/serializer/Base.js, src/data/serializer/ImageWMS.js, src/data/serializer/TileWMS.js, src/data/serializer/Vector.js, src/data/serializer/WMTS.js, src/data/store/Collection.js, src/data/store/Features.js, src/data/store/Layer.js, src/data/store/Tree.js, src/util/Symbol.js, test/load-tests.js, test/spec/GeoExt/util/Symbol.test.js
This PR adds an utility class providing methods to check for symbols of OpenLayers we depend upon.
This class can be used to check if the dependencies to external symbols are fulfilled. An example:
```javascript
Ext.define('MyNewClass.DependingOnOpenLayersClasses', {
requires: ['GeoExt.util.Symbol'],
// the contents of the `symbols` property will be checked
symbols: [
'ol.Map', // checking a class
'ol.View.prototype.constrainResolution', // an instance method
'ol.control.ScaleLine#getUnits', // other way for instance method
'ol.color.asArray', // one way to reference a static method
'ol.color::asString' // other way to reference a static method
]
// … your configuration and methods …
}, function(cls) {
// actually call `check` with the just defined class:
GeoExt.util.Symbol.check(cls); …
```
=> Automatically check for required external symbols

src/component/FeatureRenderer.js
When using proj4js together with ol3, instanciation of an ol.proj.Projection without the `code` proerpty will fail.
I will open up a Pull Request in ol3 shortly.
=> Add empty projection String to satisfy ol.proj.Projection

.travis.yml, ci/create-sencha-environment.sh, ci/create-sencha-package.sh, ci/shared.sh
This commit adds several shell scripts, which are used when running the continuous integration. They download and install all resources needed for a build using the sencha cmd. As part of the ci, we now
always try to build the GeoExt package.
Additionally the travis ci is configured to cache the contents of certain directories, which change only every now and then. This caching speeds up the following builds, where the dependencies for
Sencha or ExtJS have been resolved previously.
Please review.
/cc @weskamm, @chrismayer, @KaiVolland
=> Enable building package with sencha cmd on travis

src/component/FeatureRenderer.js, src/component/Map.js, src/component/OverviewMap.js, src/data/MapfishPrintProvider.js, src/data/model/Layer.js, src/data/model/LayerTreeNode.js, src/data/model/Object.js, src/data/serializer/Base.js, src/data/serializer/ImageWMS.js, src/data/serializer/TileWMS.js, src/data/serializer/Vector.js, src/data/serializer/WMTS.js, src/data/serializer/XYZ.js, src/data/store/Collection.js, src/data/store/Features.js, src/data/store/Layer.js, src/data/store/Tree.js, src/mixin/SymbolCheck.js, test/load-tests.js, test/spec/GeoExt/mixin/SymbolCheck.test.js
This PR suggests refactoring of the `GeoExt.util.Symbol`-class to a mixin. This gives us the opportunity to remove the explicit calls to `GeoExt.util.Symbol.check(cls)` as we can then use the `onClassMixedIn`-method, which will do this automatically.
Additionally a commit is included which tests the symbols of the recently introduced `GeoExt.data.serializer.XYZ`.
Please review.
See #59, fixes #71
/cc @chrismayer
=> Refactor symbol check class to a mixin

ci/create-sencha-package.sh, ci/shared.sh
This way we have a little feedback on e.g. the full build size.
```
Size of GeoExt.pkg = 268 kb
Size of GeoExt.js = 40 kb
Size of GeoExt-debug.js = 156 kb
```
Please review.
=> Output some build statistics on travis

src/mixin/SymbolCheck.js
A followup on #72. The placement of the `<debug>`-comments lead to a dangling comma in the final build.
The message 
```
[WRN] C1000: Rhino Parse Warning (Trailing comma is not legal in an
ECMA-262 object initializer => });) -- /tmp/sencha-workspace/
packages/geoext3/src/mixin/SymbolCheck.js:68:1
```
Is now gone on CI.
Please review.
=> Move <debug>-comments to remove a build warning

ci/update-gh-pages.sh
The gh-pages update did not succeed, because the `docresources`-folder was missing (see #80).
Please review.
=> Copy over docresources before updating gh-pages

ci/update-gh-pages.sh, docresources/eg-iframe.html
JSDuck expects the eg-iframe file to be present when it is run, so we
change the order in which we update the gh-pages resources. Additionally,
we now use an online resource of the ExtJS JavaScript for the inline
examples.
I'll merge this once travis gives green lights, as it only deals with the CI-Script.
=> Fixes for the update-gh-pages script

ci/update-gh-pages.sh
Use the -s option to suppress the diff when getting author email and name.
=> Don't print diff when getting author email

ci/update-gh-pages.sh
This PR suggests to also publish `GeoExt.js` and `GeoExt-debug.js` and associated CSS when we update the resources in the `gh-pages`-branch
=> Publish generated GeoExt-resources on gh-pages

src/data/store/LayersTree.js, test/spec/GeoExt/data/store/LayersTree.test.js
Whenever a folder gets collapsed, ExtJS seems to actually remove the children from the store, triggering the removal of the actual layers in the map. This is an undesired behviour. We handle this as follows. Before the collapsing happens, we mark the childNodes, so we effectively opt-out in #handleRemove.
Fixes #103.
Implementation again heavily inspired by @weskamm’s brain :black_joker:
Please review /cc @KaiVolland & @chrismayer.
=> Ensure node-collapsing doesn't remove layers

test/spec/GeoExt/data/MapfishPrintProvider.test.js, test/spec/GeoExt/data/store/LayersTree.test.js
This removes the annoying (no actual errors) when testing:
```
Error loading resource http://b.tiles.mapbox.com/v3/mapbox.20110804-hoa-
foodinsecurity-3month/2/1/2.png (203).
Details: Error downloading http://b.tiles.mapbox.com/v3/mapbox.20110804-hoa-
foodinsecurity-3month/2/1/2.png - server replied: Not Found
```
Cheers for any review.
=> Use an existing tileset from mapbox in tests

src/component/Map.js
This PR suggests to replace the `mouseenter` with the `mouseover` event to ensure the map's `pointerrest` event is fired as expected in IE11.
IE11 fires the `mouseenter` event if the user moves the mouse pointer inside the boundaries of the object (here the `GeoExt.component.Map`) only. If the pointer is already inside the boundaries, it wont get fired and the user has to move the pointer outside the element and back in the origin to get this event fired (see [here](https://msdn.microsoft.com/en-us/library/ms536945(v=vs.85).aspx) for further details).
The problem: Under circumstances where the pointer is moved outside the map (`mouseleave`), e.g. by a hover popup/window created just under the pointer, the user would have to move the pointer outside the map and back in to get the hover …
=> Register mouseover instead of mouseenter event on the map

src/data/store/LayersTree.js, test/spec/GeoExt/data/store/LayersTree.test.js
In ExtJs collapsing of a node in the layertree leads to a loss of children in the store. In GeoExt there is a fix for this, but it only saves the first childnodes. With this fix, all children are safe!
=> Fixed recursion on treenodes to avoid layerloss on nodecollapse

src/component/Map.js
Seems this one has been missed, as all other occurences in this class are handled this way
=> Fixed map-element reference for modern / mobile applications

test/spec/GeoExt/data/store/LayersTree.test.js
`ol.source.TileJSON` now uses XHR (see openlayers/ol3#4625) and we need to adjust our tests.
Please review.
=> Use json in LayersTree test when using TileJSON

examples/mapviewform/mapviewform.html, examples/mapviewform/mapviewform.js
This removes features from the example that depended on some experimental and rejected features of ol3 (hue, saturation as props of the layer). 
To make up for this I added a different demo of binding a boolean ol.Object  property to a checkbox. I found that to be at least a little bit interesting.. now that this example is much less colorful. :rainbow: :cry:
=> Update form example

package.json
This way we make it less likely that the coverage process stops (e.g. because
of a linting error) in the middle of the file shuffling and leaves the
repository in a messed-up state.
Fixes #123.
=> Lint JavaScript before gathering test-coverage

src/mixin/SymbolCheck.js
Fixes bug related to `mixin.SymbolCheck` described in #128.
The reasoning behind this is, that the used `/pattern/g` describes a global regex match pattern which would yield the index of the first hit correctly. With the next symbol check this index isn't dropped but the new string is checked starting from that very index again.
=> Do not use regex global modifier to match symbols

index.html
The docs use resources from openlayers.org, which aren't available via https.
The inline examples therefore do not work when th API docs are accessed via
https.
=> Link to http variants of the API docs

src/data/model/Base.js, src/data/model/Layer.js, src/data/model/print/Capability.js, src/data/model/print/Layout.js, src/data/model/print/LayoutAttribute.js, test/data/PrintCapabilities.json, test/index.html, test/karma.conf.js, test/spec/GeoExt/data/model/print/Capability.test.js, test/spec/GeoExt/data/model/print/Layout.test.js, test/spec/GeoExt/data/model/print/LayoutAttribute.test.js
Calling `Ext.create("Model", nestedPropsMap)` will result in a record of `Model` whose associations aren't populated. The reason for this is, that the configured reader is never called as would be with any remote request using a proxy. This PR adds a static method `Model.loadData` to GeoExt models to load nested property maps. This is very convenient for cases like the print capabilities which may change less often and can be put into the applications codebase without the need of further remote requests.
To test the whole thing I added tests to the print models and found some inconsistencies when interacting with associations. Migrating the `hasMany` configurations to `reference` field configurations seems to be the recommended approach dealing with relationship in ExtJS 6 anyway.
The …
=> Allow to init records from deeply nested property maps migrating print models

ci/update-gh-pages.sh
This should fix the autodepolyment by skipping the jsduck build. Just a hotfix as we still want documentation.
=> Fix autodeployment to gh-pages

src/data/store/LayersTree.js, test/spec/GeoExt/data/store/LayersTree.test.js
The treeNode removal candidate could not be found as the search was
performed only on root's direct children (no deep search). In such case when
layer is removed from group it is not being removed from tree.
=> Fix nested node removal

src/data/store/LayersTree.js, test/spec/GeoExt/data/store/LayersTree.test.js
Check issue #135 for more details.
Also added new tests that check node ordering for both inverse and non inverse layer ordering Tests cover following cases:
1. initial ordering
2. after layer being inserted
3. after layer appended
=> Fix tree's nested node ordering

src/data/MapfishPrintProvider.js, test/spec/GeoExt/data/MapfishPrintProvider.test.js
This PR fixes and simplifies the `getLayerArray` Method. The old function was too complex and lead to sort / order errors when having a deep nested tree, e.g. folder containing "sub"folder which contain layers. I added a test which ensures that layerorders keep correct
=> Fixed order of getLayerArray in PrintProvider

src/data/serializer/XYZ.js, test/spec/GeoExt/data/serializer/XYZ.test.js
This PR adds the `imageExtension` property to the serializer as it is required by the mapfish print servlet v 3.4.
The docs http://mapfish.github.io/mapfish-print-doc/layers.html#OsmLayer seem to be kind of outdated or missleading as they say `imageFormat` is required and deprecated.
A request to the printservlet unveils that `imageExtension` can be used instead:
`The OneOf choice: extension was not satisfied.  One (and only one) of the following fields is required in the request data: java.lang.String imageFormat, java.lang.String imageExtension`
=> Adds required "imageExtension" to the XYZ serializer.

examples/tree/panel.js, src/data/model/Layer.js, src/data/model/LayerTreeNode.js, src/data/store/LayersTree.js, test/spec/GeoExt/data/model/Layer.test.js, test/spec/GeoExt/data/store/LayersTree.test.js
This PR aims to improve the layer tree initialization and customization by doing the following:
* Simplify `GeoExt.data.model.Layer` attribute mapping by referring to helper function `getOlLayerProp`
* Add `text` field to `GeoExt.data.model.Layer` that is populated by sensible defaults. This field is used by the layer tree to show the layers name. It may very well be used in other model views, therefore I choose to place this here instead of `GeoExt.data.model.LayerTreeNode`. This also simplifies the layer node insertion logic of `GeoExt.data.store.LayersTree` and allows extending these objects.
* Add `tip` and `qtitle` fields to make it easy to define tooltips via the `description` property of the OpenLayers layer. 
* Add configuration properties to set the property keys that the …
=> Improve layer tree customization options

jsduck-cfg.json, src/data/serializer/XYZ.js
This PR suggests a minor change to the API docs of the XYZ-serializer: we were referencing a non-existing OpenLayers class.
Please review.
=> Fix wrong datatype in @param API doc

package.json
This PR updates several `devDependencies` to their newest version:
* [`browser-sync`](https://www.npmjs.com/package/browser-sync) to `2.12.5`
* [`eslint`](https://www.npmjs.com/package/eslint) to `2.8.0`
* [`karma`](https://www.npmjs.com/package/karma) to `0.13.22`
* [`karma-coverage`](https://www.npmjs.com/package/karma-coverage) to `0.5.5`
* [`karma-eslint`](https://www.npmjs.com/package/karma-eslint) to `2.1.0`
* [`karma-mocha`](https://www.npmjs.com/package/karma-mocha) to `0.2.2`
* [`karma-phantomjs-launcher`](https://www.npmjs.com/package/karma-phantomjs-launcher) to `1.0.0`
* To get rid of a future compatibility warning, [`phantomjs-prebuilt@2.1.7`](https://www.npmjs.com/package/phantomjs-prebuilt) is also required
* [`mocha`](https://www.npmjs.com/package/mocha) to `2.4.5`
Since …
=> Update node devDependencies

examples/component/overviewMap.js, examples/tree/panel.js, examples/tree/tree-legend-simple.js, src/component/Map.js, src/component/OverviewMap.js, src/component/Popup.js, test/spec/GeoExt/component/Map.test.js, test/spec/GeoExt/data/store/Features.test.js, test/spec/GeoExt/data/store/LayersTree.test.js
Because of the removal of ol.source.MapQuest in OpenLayers (https://github.com/openlayers/ol3/commit/ed80d243fbbeb3c414f9234f80233dd3f560c2ab) this PR removes all MapQuest sources and replaces them with appropriate other data sources.
This affects the examples, tests and live-code snippets, not the library code itself.
=> Remove OpenLayers MapQuest sources

ci/update-gh-pages.sh
In f0b17ecd1e4deccb39e50d8fe7fd3fcb316338fb (PR #133, merged 2016-03-01) we
disabled the automatic API documentation generation and publishing (via CI)
as a hotfix.
I really want have this back again and want to see if the API-doc generation
errors still occur now that 5 months of time have passed.
Anybody willing & brave enough to review this? We can only really test this once the PR is merged…
=> Reenable the API docs autoupdate

src/component/Map.js, test/spec/GeoExt/component/Map.test.js
- add removeLayer() throws error if no layer is passed test
- add addLayer() throws error if no layer is passed test
- add getStore() to be a GeoExt.data.store.Layers object getter test
=> Add several map-component tests

examples/features/grid.js, src/data/store/Features.js, test/spec/GeoExt/data/store/Features.test.js
This ensures that the FeatureStore (``GeoExt.data.store.Features``) uses the correct model class (``GeoExt.data.model.Feature``) in case of beeing instanciated with a ``fields`` configuration. Otherwise an implicit model is generated and the reference to the OL feature in the record is missing (fixes #171).
This also adds some tests and adapts the featuregrid example to show the fixed behaviour.
=> Apply correct model to FeatureStore with fields

.travis.yml, package.json
This PR suggests to update the development dependencies of GeoExt3 to the newest released versions. In detail the following updates were made:
* `browser-sync` from `v2.12.5` to `v2.15.0`
* `coveralls` from `v2.11.9` to `v2.11.12`
* `eslint` from `v2.8.0` to `v3.5.0`
* `eslint-config-openlayers` from `v4.1.0` to `v5.0.0`
* `karma` from `v0.13.22` to `v1.3.0`
* `karma-coverage` from `v0.5.5` to `v1.1.1`
* `karma-mocha` from `v0.2.2` to `v1.1.0`
* `karma-phantomjs-launcher` from `v1.0.0` to `v1.0.2`
* `karma-sinon` from `v1.0.4` to `v1.0.5`
* `mocha` from `v2.4.5` to `v3.0.2`
* `phantomjs-prebuilt` from `v2.1.7` to `v2.1.12`
* `sinon` from `v1.17.3` to `v1.17.5`
Additionally we now run the testsuite on latest Node.js (i.e. v6 currently)
Please review.
=> Update development dependencies

.travis.yml
In order to enable [greenkeeper](https://greenkeeper.io/) for this repository, we should allow travis also for the branches starting with `greenkeeper-`.
Please review.
=> Enable travis for greenkeeper branches

src/data/serializer/ImageWMS.js, src/data/serializer/TileWMS.js, test/spec/GeoExt/data/serializer/ImageWMS.test.js, test/spec/GeoExt/data/serializer/TileWMS.test.js
- This introduces the serialization of the `STYLES` Url Param as expected
by the MapFish Print
=> Adds correct styles param to WMS serializers

src/component/OverviewMap.js, test/spec/GeoExt/component/OverviewMap.test.js
This PR suggests to change the `Overview` component to also support dragging of the extent feature to recenter the parent map.
This behaviour is controllable via a new configuration `enableBoxDrag` which defaults to true, e.g. dragging is enabled.
Also included are a couple of minor fixes (mostly documentation wording, return value of appliers, inline comments).
Please review.
=> Enable dragging of extent feature in overview

test/index.html, test/karma.conf.js
With the release of OpenLayers v4, the `ol.animation` functions have been removed:
https://github.com/openlayers/openlayers/releases/tag/v4.0.0
As the tests in this project rely on the OpenLayers master branch, there is a failing test now.
This PR changes the test resources to load the latest compatible version of OpenLayers (v3.20.1)
=> Don't use OL master due to breaking changes in OL4

src/component/OverviewMap.js, test/spec/GeoExt/component/OverviewMap.test.js
I noticed that the overview map requires the same projection as the parent map.
This PR allows the overview map to use a projection that differs from the parent maps projection.
Changes basically include the transformation of coordinates/geoms, if necessary. To assure that the magnification mechanism also works initially, some effort was necessary (as resolutions had to be available on the overviewView).
Note: Tests are still missing. I'll soon try to add some.
=> Allow different projection on overview map

bin/example-generator/example.html.tpl, docresources/eg-iframe.html, examples/component/map.html, examples/component/overviewMap.html, examples/features/grid.html, examples/mapviewform/mapviewform.html, examples/popup/gx-popup.html, examples/print/basic-mapfish.html, examples/renderer/renderer.html, examples/tree/panel.html, examples/tree/tree-legend-simple.html, package.json, test/index.html
This PR suggests to change the following about how we include OpenLayers.
* for examples
* use the published OpenLayers ressources from `openlayers.org`, via `https`
* Also use the supported version, not `master`
* This way we do not need to change the deployment process for the `gh-pages`, we could later do that of course
* for development: require the `openlayers`-package (which adds some overhead), and use local versions when testing.
=> Change how we include OpenLayers

universal-app.md
This corrects the OpenLayers version to v3.20.1 (the currently supported version) in the Universal App tutorial (related to #245).
=> Set OL version to 3.20.1 in universal-app tutorial

src/component/OverviewMap.js, test/spec/GeoExt/component/OverviewMap.test.js
This PR suggests to change how we reflect rotation in Overview maps. Before this PR we would take the extent of the parent map, rotate that with the rotation of the parent map, and then create a new polygon, which we would render in the overview map. This very easily leads to images like the following, where the polygon in the overview map is way to big, and doesn't really reflect the visiblke extent of the parent map:
The approach taken in thi PR doesn't rotate at all. Instead it takes the size of the map, and queries the parent map for coordinates at the corners. This way we get the real coordinates of a rectangle we currently see. The visual outcome is what one would expect:
In total this PR removes code and simplifies it quite a bit, I think.
Please review.
Fixes #252
=> Correct extent in overviewmaps for rotated views

.gitignore, bin/external-resources.json, bin/fetch-external-resources.js, bin/util.js, package.json, test/karma.conf.js
This PR suggests to add a `postinstall`script, which will download the ExtJS requirements (CSS and JS in standard and debug variants) and store them in a local (but ignored by `git`) folder.
The karma runner uses these files and I can see quite a speed-up in the execution of the testsuite.
Please review.
=> Use more local resources

examples/print/basic-mapfish.js, src/data/MapfishPrintProvider.js
This PR suggests to change the print example so that only http-resources are send as layers, as the used MapFish instance has issues with https requests.
Also on API doc is changed in a MapfishPrintProvider method.
Please review.
Fixes #253
=> Fix the print example

src/component/Map.js, test/.eslintrc, test/TestUtil.js, test/index.html, test/karma.conf.js, test/spec/GeoExt/component/Map.test.js
This PR sugests to add a test utility, that makes the actual tests little less verbose, especially when it comes to set up / teardown `<div>`-elements, instances of `ol.Map` or instances of `GeoExt.component.Map`.
The utility is used in the map component tests, to which I have some more as well. Coverage now is at `85.1%`
Please review.
=> Add a test utility and improve test coverage

package.json
Before releasing `v3.0.0` I want to make sure that our development dependencies are as up to date as possible.
* Update coveralls to v2.12.0
* Not exactly sure why the coverage decreases by ~ 3.5%, but since we do not enforce a hard limit, I don't really care right now
* The same happened in [another repo](https://github.com/terrestris/BasiGX/pull/154)
* The raw numbers are also unchanged:
* master:
* 60.3 hits per line
* 1029 of 1210 relevant lines covered (85.04%, my calculation)
* Summary says: 85.04%
* This PR:
* 60.3 hits per line
* 1029 of 1210 relevant lines covered  (85.04%, my calculation)
* 408 of 553 branches covered (73.78%, completely new)
* Summary says: 81.50%
* Update eslint to v3.17.1 (Unproblematic)
=> Update npm development dependencies

ci/update-gh-pages.sh
This PR is WIP until we have released `v3.0.0`.
Previously we would publish a sencha package for every commit that
happened in the `master`-branch. This commit changes this in a way
that only tagged commits (released versions) will publish a sencha
package.
We still need to define how we actually want to react when we build
for say `v3.0.1`. The current approach would probably make the
originally published `v3.0.0` unusable (because we `rm` probably too
much, and also copy over `catalog.json` metatdata files where we
actually want to merge new `catalog.json` with existing ones).
Comit 21299d8 temporary disables the publishing alltogether,
so we cannot break any existing published package.
=> Publish only tagged packages

universal-app.md
This updates the tutorial showing how to create an GeoExt-based universal app to latest development state of GeoExt. Focus is on the recommended installation of GeoExt as git clone. The integration as ExtJS package remains as alternative way doing this.
@jgrocha: The links to the online examples (http://mygeoextapp.geomaster.pt/ and http://geodashboard.geomaster.pt/#map) provided by you do not work anymore. Will you perovide them again or should we remove the links?
Please review.
=> Update universal-app tutorial to current development state

src/data/store/Features.js
This fixes the following rendering:
When API doc blocks start with `#` they aren't interpreted as links, but as headings.
Please review.
=> Reformat API docs for better rendering

src/data/store/LayersTree.js
- This renames `onBeforeGroupNodeCollapse` to `onBeforeGroupNodeToggle`.
- It adds the listener function to the expand event aswell as. Thats why i renamed it.
Solves issue #302.
=> Introduces onBeforeGroupNodeToggle

src/component/FeatureRenderer.js, src/component/OverviewMap.js, src/data/MapfishPrintProvider.js, src/data/model/OlObject.js, src/mixin/SymbolCheck.js, src/util/Layer.js
This replaces `statics` with `inheritableStatics` to avoid problems when extending this component.
e.g.: `me.self.getVisibleExtentGeometries` inLine 537 is undefined currently when extending the component.
=> Replace statics with inheritableStatics

src/data/store/Features.js, src/data/store/Layers.js, src/data/store/OlObjects.js
This adds the ``@private``-tag to the internal handler functions in the store-classes (``GeoExt.data.store.`*``).
So they do not appear as public API-functions in the API-docs.
=> Add @private-tags to internal handlers in store classes

src/component/FeatureRenderer.js, src/component/Map.js, src/component/OverviewMap.js, src/data/serializer/Vector.js, src/data/store/LayersTree.js, src/util/Version.js, test/karma.conf.js, test/spec/GeoExt/component/OverviewMap.test.js, test/spec/GeoExt/util/Version.test.js
- This introduces GeoExt.util.Version which can be used to determine if ol3
or ol4 is used.
- GeoExt.util.Version will be required in GeoExt.component.Map to be available
right when you use a map.
- It adds checks for `ol.animation` and `ol.View.fit()` which are the breaking changes.
Solves #243
=> Support for ol v4.x.x

README.md, bin/example-generator/example.html.tpl, docresources/eg-iframe.html, examples/component/map.html, examples/component/overviewMap.html, examples/features/grid.html, examples/filtered-heatmap/filtered-heatmap.html, examples/mapviewform/mapviewform.html, examples/popup/gx-popup.html, examples/print/basic-mapfish.html, examples/renderer/renderer.html, examples/tree/panel.html, examples/tree/tree-legend-simple.html, package.json, universal-app.md
This prepares the upcoming release of GeoExt in the version 3.1.0:
- Using latest OpenLayers v4.3.2 in the devDependencies (and re-enable greenkeeper for OL)
- Using latest OpenLayers v4.3.2 in the examples
- Update the versions documented in the README, so it will be consistently documented in the release package
- Complete the listed examples in the README
After this is approved and merged the release can be done. I will come up with another PR adapting the ``gh-pages`` branch afterwards.
IMHO also closes #243 
Please review.
=> Prepare GeoExt v3.1.0 release

package.json
Because of releasing GeoExt v3.1.0 this increases the version number in the package.json for the next development cycle.
=> Set GeoExt version to 3.1.1-dev

index.html
Show v4.4.x as the currently supported OL-version in the master branch of GeoExt on the website.
=> Update documentation for supported OL version in master

src/data/store/Layers.js
This adds the missing two parameters ``details`` and ``eOpts`` for the handler function when triggering the LayerStore's 'update'-event when changing the underlying OpenLayers layer. Otherwise an exception occurred because some ExtJS code tried to access the undefined parameters.
The issue was noticed in a setup with the modern toolkit of ExtJS.
See here: https://docs.sencha.com/extjs/6.2.1/modern/Ext.data.Store.html#event-update
=> Add handler params for LayerStore's 'update'-event

examples/modern-layerlist/modern-layerlist.html, examples/modern-layerlist/modern-layerlist.js, examples/modern-map/modern-map.html, examples/modern-map/modern-map.js
This adds two examples using the modern toolkit of ExtJS:
1) Show how to use the <code>GeoExt.component.Map</code> class in an GeoExt app with the modern toolkit
2) Show how to use an <code>Ext.grid.Grid</code> component with a <code>GeoExt.data.store.Layers</code> to let the user change the visibility of the map layers in an GeoExt app with the modern toolkit
Once we have agreed on merging this, we can list them in the README and on the GeoExt website.
TIA for any review.
=> Add first two examples for modern toolkit

README.md
This adds the links to the examples built with the modern toolkit (introduced by #397) to our README file.
=> Add links to modern toolkit examples to README

index.html
This adds a new section for modern toolkit examples to the GeoExt3 website and lists the newly created examples based on the modern toolkit (see #397):
TIA for any review.
=> Add section for modern toolkit examples to website

src/data/serializer/Vector.js
When trying to print/serialize redlining/measure layers, two problems were found:
* The geojson would include the parentFeature property. Being a reference to an ol feature, json serialization would fail because of cycles.
* Evaluating the style function would yield a single style, not an array of styles. This case had not been handled, resulting in the feature being skipped completely.
This PR fixes both issues.
@weskamm @marcjansen @terrestris/devs please review
=> Fix printing of redlining layers

examples/modern-layerlist/modern-layerlist.js, src/data/store/Features.js, src/data/store/OlObjects.js, test/spec/GeoExt/data/model/Feature.test.js, test/spec/GeoExt/data/store/Features.test.js, test/spec/GeoExt/data/store/OlObjects.test.js
Due to the inheritance between the `Features` store and the `OlObjects` depending on your configuration it was possible that eg. deleting a feature on the `ol.Collection` would result in deletion of two features instead of one due to listeners on the `ol.Collection` and the datasource of the underlying layer. This PR attempts to fix that.
@terrestris/devs @weskamm Please review carefully, the setup in the constructors is somewhat complicated.
=> Fix usage of collection events

src/data/serializer/Vector.js, test/spec/GeoExt/data/serializer/Vector.test.js
This adds a `geometryType` parameter to the `getUid` function.
This is needed as we can pass an ol style which might cover multiple types of geometries.
e.g:
```javascript
var style = new ol.style.Style({
fill: new ol.style.Fill({
color: 'rgba(255, 255, 255, 0.2)'
}),
stroke: new ol.style.Stroke({
color: '#ffcc33',
width: 2
}),
image: new ol.style.Circle({
radius: 7,
fill: new ol.style.Fill({
color: '#ffcc33'
})
})
});
```
This style covers `Point`, `LineString` and `Polygon`. But the old `getUid` function would return the same uid for every new call with the same `ol.style.Style`. Which leads to an overwrite of the symoblizer in the mapfishStyleObject in the `encodeVectorStyle` function.
=> Adds geometryType param to getUid function

src/component/OverviewMap.js
`beforeRender` is removed at least in the 4.6 line.
@KaiVolland Please review.
=> Fix missing symbol warning on newer ol4 versions

examples/state/stateful-map.html, examples/state/stateful-map.js, src/component/Map.js, src/state/PermalinkProvider.js, test/index.html, test/spec/GeoExt/state/PermalinkProvider.test.js
This adds an implementation of `Ext.state.Provider` to manage the app's map state and to (de)serialize it as URL hash. Currently the following properties are managed:
- Map Zoom (`zoom`)
- Map Center (`center`)
- Map Rotation (`rotation`)
=> Introduce a PermalinkProvider

bin/example-generator/example.html.tpl
This is a follow-up of #450. The HTML template for the example-generator script (`npm run generate:example foo`) uses now also the local OL build files instead of the remote ones.
=> Use local OL build file in example HTML template

src/data/model/LayerTreeNode.js
This adds another field `'iconCls'` to the fields of `LayerTreeNode` model class (`GeoExt.data.model.LayerTreeNode`). The value is derived from the underlying OL-object.
`'iconCls'` is normally used to influence the rendered icon of the `LayerTreeNode`.
=> Add iconCls to LayerTreeNode model as field

src/data/serializer/Vector.js
Since loaded images are not necessarily requestable/accessible by the print service this PR encodes icons as data urls.
@terrestris/devs Please review.
=> Encode icons as data uri

src/data/store/Layers.js, test/spec/GeoExt/data/store/Layers.test.js
This allows the creation of a `LayerStore` instance with a collection of OpenLayers layers (`ol.Collection.<ol.layer.Base>`). So there is no need to pass a complete map object, from which the layers are derived. This can be useful for several use cases, where just a subset of layers has to be manged by the store.
The old behaviour by creating with an OpenLayers map instance is still possible.
=> Allow creation of LayerStore with layer collection 

src/data/store/Layers.js, test/spec/GeoExt/data/store/Layers.test.js
This ensures the `destroy` function of the `LayerStore` calls `unbindMap` instead of the not existing `unbind` function.
Fixes #490
=> Fix broken 'destroy' function in LayerStore 

examples/features/grid-filter.html, examples/features/grid-filter.js, src/util/OGCFilter.js, test/spec/GeoExt/util/OGCFilter.test.js
This PR adds a new utility class which can be used to generate OGC compliant filters based on ExtJS grid filters.
An example has been added to showcase the power of the util by `live-filtering` WMS and WFS layers through the filters that get set by the user in the grid.
=> Introducing the OGCFilter util

src/state/PermalinkProvider.js
This fixes the broken loading of the `PermalinkProvider` class in apps using the modern toolkit due to the fact that `Ext.state.Provider` is not available in the modern toolkit (see #457).
This is done by adding the `onClassCreated` callback to `PermalinkProvider`, which defines the missing `Ext.state.Provider` as empty stub.
This also adds a warning to the API-docs of the `PermalinkProvider` class, which states that this component is only usable with the classic toolkit.
=> Fix broken loading of PermalinkProvider in modern apps

.travis.yml
This (temp.) deactivates the creation of the Sencha Package for GeoExt since this breaks the whole CI chain (see https://travis-ci.org/geoext/geoext3/builds/520762857?utm_source=github_status&utm_medium=notification).
Since CI seems not to work properly anyway (#464) and needs an overhaul and we do not recommend to use GeoExt as Sencha Package it seems OK for the moment to deactivate this.
Any concerns / ideas?
=> Deactivate Sencha Package creation on CI

examples/geocoder/geocoder-combo.html, examples/geocoder/geocoder-combo.js, src/form/field/GeocoderComboBox.js, test/index.html, test/spec/GeoExt/form/field/GeocoderComboBox.test.js
This adds a generic `GeocoderCombo` component similar to those we had in previous GeoExt versions.
To sum it up it is a combo box that handles results from a geocoding service. By default it uses OSM Nominatim, but the component offers all config options to overwrite in order to use other custom services.
The component is only usable with the classic toolkit. An appropriate `onClassCreated` callback for not breaking modern apps is implemented. Also a warning is placed in the API docs.
=> Add a generic GeocoderCombo component

src/plugin/layertreenode/ContextMenu.js, test/spec/GeoExt/plugin/layertreenode/ContextMenu.test.js
This PR adds an (abstract) plugin for an `Ext.tree.Column` used in an `Ext.tree.Panel` acting as "LayerTree" in order to render a custom UI component on right-click of a `LayerTreeNode`, e. g. a menu (like `Ext.menu.Menu`).
In order to customize the UI, which is rendered the `createContextUi` function has to be implemented / overwritten.
=> Add ContextMenu plugin for columns in a LayerTree 

src/form/field/GeocoderComboBox.js
Just added an empty object as second argument to `Ext.define` to get things (dev and production build for classic and modern) running again.
@marcjansen please review
=> Fixup empty stub for GeoCoder combo in modern app

src/util/OGCFilter.js, test/spec/GeoExt/util/OGCFilter.test.js
Prevent building and sending of [invalid](http://schemas.opengis.net/filter/2.0/filter.xsd) OGC filters without body like `<Filter></Filter>`, if no ExtJS filter were provided.
=> Fix empty invalid OGC filters

README.md, classic/README.md, classic/form/field/GeocoderComboBox.js, classic/state/PermalinkProvider.js, test/karma.conf.js
This introduces a separate 'classic' folder for components, which only work with the classic toolkit of ExtJS.
Also moves the two existing "classic-only" components (`StateProvider` and `GeocoderCombo`) to this folder.
In order to use this "classic-only" components in an application configure the app's `classpath` in the app.json like:
```javascript
"classpath": [
"app",
"./lib/geoext3/src/",
"./lib/geoext3/classic/"
],
```
While modern-users would simply have:
```javascript
"classpath": [
"app",
"./lib/geoext3/src/"
],
```
=> Introduce separate 'classic' folder

classic/form/field/GeocoderComboBox.js, test/spec/GeoExt/form/field/GeocoderComboBox.test.js
Adds a config option `proxyRootProperty` to the `GeocoderCombo` component in order to overwrite the property in the JSON response of the geocoding service used in the store's JSON reader as root object.
=> Make rootProperty of JSON reader in GeocoderCombo configurable

examples/geocoder/geocoder-combo.js, examples/state/stateful-map.js
This fixes the broken loading of the classes, which are only usable with the classic toolkit in the examples. Since we use the `Ext.Loader` in the examples, which is only capable of loading one source folder for the `GeoExt` namespace, the classic components need to be loaded separately.
=> Fix loading of "classic-only" sources in examples

src/util/OGCFilter.js, test/spec/GeoExt/util/OGCFilter.test.js
This PR adds support for `lte` and `gte` filters which will result in `<PropertyIsLessThanOrEqualTo>` and `<PropertyIsGreaterThanOrEqualTo>` to be produced.
Please review.
=> Support lte and gte filters

package.json
Watch the `classic` folder when synchronizing with the browser while running `npm start`.
=> Add browser sync for classic folder

classic/toolbar/WfsPaging.js, examples/features/grid-paging.html, examples/features/grid-paging.js, src/data/store/WfsFeatures.js, test/data/wfs_mock.geojson, test/index.html, test/spec/GeoExt/data/store/WfsFeatures.test.js, test/spec/GeoExt/toolbar/WfsPaging.test.js
This PR adds a store to load features from an OGC WFS (`GeoExt.data.store.WfsFeatures`). So WFS features can easily managed and used with common UI components (e.g. grids).
In order to provide a paging mechanism for WFS data a custom WFS PagingToolbar (`GeoExt.toolbar.WfsPaging`) is also introduced by this PR.
See the provided example how to use these two components together.
=> WFS FeatureStore and WFS PagingToolbar

src/data/store/WfsFeatures.js
Not all WFS servers support the sortBy parameter. For example passing this to a MapServer WFS using a MS SQL Server driver returns the following error:
`<ows:ExceptionText>msWFSGetFeature(): WFS server error. Layer Points does not support sorting</ows:ExceptionText>`
This pull request allows a store to disable sending the sortBy parameter to the server by setting `remoteSort: false` whilst still allowing local sorting with a sortParameter.
=> Only send the sortBy parameter when remoteSort is true

classic/selection/FeatureModel.js, examples/features/grid-map-selection.html, examples/features/grid-map-selection.js, test/index.html, test/spec/GeoExt/selection/FeatureModel.test.js
This adds an extended row-selection model, which enables automatic selection of features in the map when rows are selected in a feature grid and vice-versa.
This does not use an `ol.interaction.Select` by purpose to keep it simple and flexible. A simple `singleclick` handler is registered to the map (if configured), which syncs with the grid in case a feature has been clicked.
If needed we can easily introduce an `ol.interaction.Select` later on (if really needed). Maybe by adding a second "actionMode" to the `GeoExt.selection.FeatureModel` or by sub-classing or similar. The architecture of this FeatureModel would let us this freedom  in the future.
=> Add GeoExt.selection.FeatureModel

test/TestUtil.js, test/spec/GeoExt/data/store/WfsFeatures.test.js
Before:
```
> @geoext/geoext@3.2.0 test /home/mjansen/code/geoext3
> karma start test/karma.conf.js --single-run
13 06 2019 10:04:48.603:INFO [karma-server]: Karma v4.1.0 server started at http://0.0.0.0:9876/
13 06 2019 10:04:48.606:INFO [launcher]: Launching browsers PhantomJS with concurrency unlimited
13 06 2019 10:04:48.611:INFO [launcher]: Starting browser PhantomJS
13 06 2019 10:04:48.823:INFO [PhantomJS 2.1.1 (Linux 0.0.0)]: Connected on socket -AveLfXOZGlks5mdAAAA with id 26305287
................................................................................
................................................................................
................................................................................
.............................................................. …
```
=> Remove log output when testing

src/data/store/WfsFeatures.js
This pull request adds a couple of new config options to `GeoExt.data.store.WfsFeatures`
`cacheFeatureCount` and `featureCountOutputFormat`. 
Unfortunately, MapServer doesn't support getting the feature count as part of a GeoJSON object, only GML. OpenLayers support for WFS 2.0.0 and reading features using GML doesn't seem to be supported in OpenLayers 4.6.5. 
See discussions on the MapServer mailing list at https://lists.osgeo.org/pipermail/mapserver-users/2019-June/081190.html
Support for the resultType=hits using GeoJSON isn't supported in MapServer (and maybe not GeoServer). The `featureCountOutputFormat` option allows this to be set independently of `outputFormat`. GML3 is set as the default as this seems the most universally supported type. 
The getTotalFeatureCount function is …
=> Cache feature count using resultType hits in the WfsStore

bin/util.js, development.md
If the environment variable `NO_DOWNLOAD_PROGRESS` is set to `true`, we will not be polluting stdout with progress symbols.
By default we'll keep the old behavior of showing a progress bar for the user while we download external resources.
The development instructions have been updated to reflect this possibility.
Please review.
=>  Allow download progressbar to be hidden with environment variable 

src/util/OGCFilter.js
The `getOgcFilterBodyFromExtJsFilterObject` function in `GeoExt.util.OGCFilter` contains the following:
`
var operator = filter.getOperator();
`
When using a list filter on a grid such as:
```
filter: {
type: 'list',
labelField: 'name',
idField: 'name',
```
The operator is set to `In`. If only one list item is selected then the following filter is created. Note there is an Or clause but only one value:
```xml
<Filter xmlns="http://www.opengis.net/ogc"><Or><PropertyIsEqualTo><PropertyName>PropName</PropertyName><Literal>myval</Literal></PropertyIsEqualTo></Or></Filter>
```
This throws an error in MapServer: `msWFSGetFeature(): WFS server error. Invalid or Unsupported FILTER in GetFeature`
This pull request only adds the `Or` element when there are more than one items selected in the list …
=> Check for multiple values in Or filter

src/data/store/WfsFeatures.js
Also pass parameters similar to https://docs.sencha.com/extjs/6.2.0/classic/Ext.data.Store.html#event-load including the `successful` flag. This allows any loadMasks to be hidden on an associated grid by listening to the event. 
MapServer seems to return a `Status: 403 Server processing failed ` header if an y WFS filter causes 0 records to return (unsure if this is to spec or an error in MapServer). 
```
<ows:ExceptionReport xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:ows="http://www.opengis.net/ows/1.1" version="2.0.0" xml:lang="en-US" xsi:schemaLocation="http://www.opengis.net/ows/1.1 http://schemas.opengis.net/ows/1.1.0/owsExceptionReport.xsd">
<ows:Exception exceptionCode="OperationProcessingFailed" locator="mapserv">
<ows:ExceptionText>msWFSGetFeature(): WFS server …
```
=> Fire gx-wfsstoreload on failure

src/data/store/WfsFeatures.js, test/spec/GeoExt/data/store/WfsFeatures.test.js
Allows custom options to be configured on the layer generated by `GeoExt.data.store.WfsFeatures`.
This allows options such as `opacity` and `displayInLayerSwitcher` to be set when configuring the store.
=> Allow custom options on a WfsFeatures layer

src/data/store/WfsFeatures.js, test/data/wfs_mock.geojson, test/spec/GeoExt/data/store/WfsFeatures.test.js
This pull request allows sorting of the WFS store by passing the WFS server a sortBy querystring based on the sorters in the store. 
If multiple sorters are specified then multiple fields are sent to the server. Ascending sorts append +A and descending sorts +D. E.g. sortBy=attribute1+D,attribute1+A
=> Implement sorting of the WFS store with tests

examples/features/grid-paging.js
Fix PR fixes the grid-paging example by setting sorters config and enable remote sorting.
=> WfsFeatures store example - set sorters config

examples/features/grid-spatial-filter.js, src/util/OGCFilter.js, test/spec/GeoExt/util/OGCFilter.test.js
This PR adds the missing support for Filter Encoding 2.0 that is required for WFS requests.
Resolves issue https://github.com/geoext/geoext3/issues/568
=> OGCFilter - Support for for Filter Encoding 2.0 - WFS 2.0

classic/form/field/GeocoderComboBox.js, examples/geocoder/geocoder-combo.js
This MR adds a further flag to `GeocoderComboBox` that allows restriction nomination query to current map extent (parameter `viewbox`). Restriction can be enabled / disabled for an already created component by events 'restrictToMapExtent' / `unRestrictMapExtent`.
As example is included as well.
=> Apply viewbox to GeocoderComboBox

classic/toolbar/WfsPaging.js
Use the [onBindStore](https://docs.sencha.com/extjs/6.2.0/classic/Ext.toolbar.Paging.html#method-onBindStore) prototype for setting up the events rather than onOwnerStoreChange. 
The latter worked when the store was bound automatically when the paging toolbar was added at the root of dockedItems, but when it was nested (such as in the example below) using a bind parameter it wasn't called. In this case onBindStore did get called. 
```js
dockedItems: [{
xtype: 'toolbar',
dock: 'top',
items: [
{
xtype: 'gx_wfspaging_toolbar',
displayInfo: true,
bind: {
store: '{features}'
}
},
```
=> Use prototype onBindStore for WfsPaging

test/spec/GeoExt/component/Popup.test.js
This PR adds a further test for `GeoExt.component.Popup` component whether popup can be created if not render target was specified.
=> GeoExt.component.Popup - Add test if component can be created

src/data/store/Layers.js, test/spec/GeoExt/data/store/Layers.test.js
In particular:
* pass optional filter function to `onChangeLayer` by a new config `changeLayerFilterFn`
* if not set or no result returned by `changeLayerFilterFn`, the already existing check will be applied.
* handle `description` / `qtip` property
* adds some tests
=> Layers store - Improve handler for layer changes

src/data/store/WfsFeatures.js
This is to address #567 where a previous async request could overwrite records returned from a more recent request. 
The current request is stored as a class property, and on any new request the last request is aborted. 
The onDestroy is added to clean up any referenced request. 
This also addresses #550 which is a similar related issue - two requests made in quick succession. 
I'm unsure how this could be tested.
=> Abort previous WfsFeatures requests on new request

src/data/store/WfsFeatures.js
Add the srsName param value used in the WFS request allowing features to be reprojected. 
If not set manually on the class then the srsName is automatically set to the map projection when available.
=> Add a srsName parameter to WFS calls

src/data/store/WfsFeatures.js
The parent class Ext.data.store has a [doDestroy](https://docs.sencha.com/extjs/6.5.3/classic/Ext.data.Store.html#property-doDestroy) method rather than `onDestroy` so use this. 
Alerted by build warning in SenchaCmd:
`[WRN] C1014: callParent has no target (me.callParent in GeoExt.data.store.WfsFeatures.onDestroy) -- geoext3\src\data\store\WfsFeatures.js:473:14246`
=> Change onDestroy to doDestroy

src/data/store/WfsFeatures.js, test/spec/GeoExt/data/store/WfsFeatures.test.js
This pull request adds a [propertyName](https://docs.geoserver.org/latest/en/user/services/wfs/reference.html) parameter to the store, and then forward this on to the WFS server. 
Setting only the properties required can greatly reduce the data returned from the server. A use case is to only return data for visible properties in a grid based on the WfsFeatures store. 
A sample JS snippet for a grid to check visible columns, add in the model's idProperty, and set the `propertyName` on the store is shown below:
```js
var visibleColumnNames = Ext.Array.pluck(grid.getVisibleColumns(), 'dataIndex');
var store = grid.getStore();
var idProperty = store.model.prototype.idField.name;
// add the idProperty as the first item in the list
// if it does not exist
if …
```
=> Add WFS propertyName parameter

src/data/store/WfsFeatures.js
This ensures that the config option `autoLoad` of the `GeoExt.data.store.WfsFeatures` is respected so setting `autoLoad=false` avoids loading the store on creation.
=> Respect 'autoLoad' config for WfsFeaturesStore

src/component/Map.js
When using the additional config `ignorePointerRestSelectors`, the
pointerrest and pointerrestout events of the `GeoExt.Component.Map`
will be prevented from firing, if the mouse is hovering over an
element that matches at least one of the given css selectors.
This feature comes in handy, e.g. when no events should be fired,
while hovering over tooltips.
Backwards compatibility is maintained by setting `[]` as default
for the config.
=> Introduces ignorePointerRestSelectors

classic/selection/FeatureModel.js
Allow `layer`, `map`, `mapSelection`, and `selectStyle `to all be bindable. 
This allows the properties to be stored and updated in an associated viewModel, and the selModel to be configured similar to below:
```
selModel: {
type: 'featuremodel',
mode: 'SINGLE',
mapSelection: true,
bind: {
map: '{map}'
}
selectStyle: {
bind: '{selectStyle}'
}
},
```
=> Make GeoExt.selection.FeatureModel properties bindable

src/data/store/WfsFeatures.js
Catch any parsing errors when converting from a WFS respnse to the OpenLayers format. 
Without catching this any stores with loading masks will become unusable. 
A WFS server can often return an error, which has a valid HTTP code (200), but instead of features returns an error message as HTML. If an attempt to parse this is made then an exception occurs.
=> Catch WFS Parsing Errors

bin/util.js, package-lock.json, package.json
Patch `http` & `https` modules to use a proxy configured with e.g. environment variables `http_proxy`, `https_proxy` … or `https-proxy`, `http-proxy` & `proxy` npm configs will be used.
@buehner this might be of use for you, please review.
=> Respect a proxy set in env or npm config

.sencha/package/sencha.cfg
To create a full and minified build of the GeoExt library the new classic folder and source files should be included. 
The commands below can then be run as per the instructions at https://github.com/geoext/geoext3/blob/master/CONTRIBUTING.md#sencha-cmd
```
SET PATH=D:\Tools\Sencha\Cmd\6.2.2;%PATH%
cd geoext3
sencha -sdk D:\Tools\Sencha\ext-6.2.0 generate workspace .
sencha package build
```
This then creates output files in `build\@geoext` e.g. `geoext.js` (minified) and `geoext-debug.js` - single file unminified. 
@chrismayer - this is the method I use for a single file build - you asked on the mailing list [1] - I did reply but I don't think the mail got through. 
See also #406. 
[1] https://www.geoext.org/pipermail/users/2019-October/003575.html
=> Add classic source folder to classpath for single file builds

src/util/OGCFilter.js
This adds a function `combineFilterBodies` to `GeoExt.util.OGCFilter`.
It combines the passed OGC filter bodies with an `<And>` or `<Or>` and returns them. Filter bodies could for example be created with `GeoExt.util.OGCFilter.getOgcFilterBodyFromExtJsFilterObject`.
=> Add "combineFilterBodies" to OGCFilter util

src/data/MapfishPrintProvider.js, test/spec/GeoExt/data/MapfishPrintProvider.test.js
This PR suggests to explain why we need an external URL in the test (JSONP), and store it in a variable to be less error-prone.
Additionally a typo is fixed.
=> Small test enhancements

src/data/model/LayerTreeNode.js
Fixes ol3 tree mode to only update layer visibility as specified.
=> Fix ol3 tree node mode

src/data/model/LayerTreeNode.js, src/data/model/OlObject.js, src/data/serializer/Base.js, src/data/store/LayersTree.js, src/mixin/SymbolCheck.js, src/util/OGCFilter.js
Also reformat lines where eslint found line-length issues afterwards.
Please review.
=> Fix common misspellings with codespell

test/data/staticPrintCapabilities.jsonp, test/spec/GeoExt/data/MapfishPrintProvider.test.js
This PR suggests to no longer rely on a webservice which might at times be unreachable or to slow, and instead use a local resource when testing the jsonp-variant of the `MapfishPrintProvider`.
As soon as the automatically invoked `./bin/fetch-external-resources.js` has downloaded the standard ExtJS resources once, this  will result in completely oflline capable tests.
Fixes #630
=> Become offline testable by using a static local resource for JSONP

.travis.yml
Until we have maybe moved to GitHub actions, this might speed up CI builds on Travis.
This saves us ~6 seconds ([1m30s](https://travis-ci.org/github/geoext/geoext3/builds/761635172) vs. [1m24s](https://travis-ci.org/github/geoext/geoext3/builds/761637931)) isn't that … well it isn't much but doesn't hurt :man_facepalming:
=> Cache external resources in Travis CI

package-lock.json, package.json, test/karma.conf.js
This adds and configures [a summary reporter](https://www.npmjs.com/package/karma-summary-reporter):
```
npm test
…[skipped a lot]…
SUMMARY
0: Chrome Headless 88.0.4324.182 (Linux x86_64): Executed 390 of 390 SUCCESS (9.384 secs / 4.165 secs)
1: Firefox 85.0 (Ubuntu 0.0.0): Executed 390 of 390 SUCCESS (10.388 secs / 4.341 secs)
384 test cases successful in all browsers
```
Can also be configured to look e.g. like this:
```
#createSpatialFilter
is defined                                  ✔    ✔  ✔ 
returns null for invalid operator type      ✔    ✔  ✔ 
returns a valid spatial filter              ✔    ✔  ✔ 
GeoExt.util.Version
basics
is defined                                    ✔    ✔  ✔ 
```
This is completely open for feedback, we can very much also live without this dependency, but I …
=> Use a 'summary' reporter for unit tests

.github/workflows/on-pull-request.yml, .github/workflows/on-push-master.yml
This is an attempt to build `master/GeoExt.js` and friends with the help of the sencha command during CI. This can only really be tested if it is merged :man_shrugging: 
I'd really like to have this generated differently, this must be possible, right? wasn't there some npm replacement for `sencha`? Maybe [here](https://www.npmjs.com/package/extjs-dependencies), [here](https://www.npmjs.com/package/grunt-extjs-dependencies-minimatch) or [here](https://www.npmjs.com/package/gulp-extjs) ar nice helpers.
Fixes #675
=> Build GeoExt*.js during CI w/ sencha cmd

src/data/store/WfsFeatures.js
#589 aborts requests if a new request is made to the store. This causes a `failure` response and a warning to be logged. As every initial load of the store triggers 2 requests hiding the warning in this case removes log clutter.
=> Don't log WfsFeatures warnings if the transaction is aborted

src/data/MapfishPrintProvider.js
This adds missing requires for `MapfishPrintProvider` that lead to errors on production builds.
=> Add Missing Requires

index.html
This changes all links inside of https://geoext.github.io/geoext/
from https://geoext.github.io/geoext3/ to https://geoext.github.io/geoext/
from https://github.com/geoext/geoext3 to https://github.com/geoext/geoext
=> Rename links inside gh-pages from geoext3 to geoext

.github/workflows/on-push-master.yml, .github/workflows/on-tag.yml
This deploys the gh pages also to https://geoext.github.io/geoext3/ (not only to https://geoext.github.io/geoext). This ensures that any existing links to the api docs will still work in the future.
=> Deploy gh pages to geoext3

src/data/store/Layers.js
This is a follow up to https://github.com/geoext/geoext/pull/683
It merges two functions and makes a function call clearer.
Also this uses the filter function only in onChangeLayer as before.
=> Followup for layer synchronization

classic/selection/FeatureModelMixin.js
Fix for #692 - creating the `ol.Collection()` in the same place as adding the listeners ensures the correct collection is used. 
Still unsure why `bindFeatureModel` is called multiple times in my application. 
Unable to request a review so pinging @simonseyock directly. 
Fixes https://github.com/compassinformatics/cpsi-mapview/issues/411
=> Ensure correct selectedFeatures is used for GeoExt.selection.FeatureModelMixin

classic/selection/FeatureModelMixin.js, test/spec/GeoExt/selection/FeatureRowModel.test.js
If a feature is selected and then removed from a layer an error is thrown. The issue is caused due to the logic in [Ext.util.Collection](https://docs.sencha.com/extjs/6.7.0/classic/Ext.util.Collection.html#method-itemChanged
) (although it may not be a bug in ExtJS). 
In the `itemChanged` function the feature is already removed, so when searched for by key `filterChanged` is set to `true`:
```js
if (filtered) {
index = me.indexOfKey(keyChanged ? oldKey : newKey); //  as the array is empty then index is -1
wasFiltered = (index < 0); // this is then true
itemFiltered = me.isItemFiltered(item);
filterChanged = (wasFiltered !== itemFiltered); // also then true
```
Then the `toAdd` array is populated which triggers an `add` event which adds a record to the store, even when everything is …
=> Fix for removing a selected features throwing a key error

src/data/store/WfsFeatures.js, test/spec/GeoExt/data/store/WfsFeatures.test.js
This pull request moves the WFS request parameter creation out of the `loadWfsInternal` function in `GeoExt.data.store.WfsFeatures` and into its own function.
This allows the store logic to be used to download the contents of the store in another `outputFormat` for example:
```js
var url = store.url;
var params = store.createParameters();
params.outputFormat = 'shapezip'; // change the outputFormat for the current store contents
// now we can request the same data in the store with a different format (if supported by the WFS server)
// files can't be downloaded using Ext.Ajax.request (due to browser security)
// so a hidden form is used with standardSubmit set to true
// this approach does not allow callbacks to be run on success / failure
Ext.create('Ext.form.Panel', {
standardSubmit: …
```
=> Extract WFS Store parameter creation to its own function

examples/features/grid-filter.js, examples/features/grid.js, examples/filtered-heatmap/filtered-heatmap.js
Fixes the following examples:
* https://geoext.github.io/geoext/master/examples/filtered-heatmap/filtered-heatmap.html is broken and fails with `GeoExt.data.store.Features needs to be configured with a feature collection or with a layer with a source with a feature collection`, most probably broken since #686 
* https://geoext.github.io/geoext/master/examples/features/grid.html has the same issue
* https://geoext.github.io/geoext/master/examples/features/grid-filter.html  has the same issue
See #704
=> Fix broken examples after #686

examples/features/grid-map-selection.js
This PR fixes the currently broken https://geoext.github.io/geoext/master/examples/features/grid-map-selection.html example.
See also #704.
Please review.
=> Fix the grid map selection example

src/component/OverviewMap.js
This fixes the problem described in https://github.com/geoext/geoext/issues/707
When using the OverviewMap with a custom map object, since updating to OL 6.5.0, it is now expected that this custom map object also has (any) center value set. This change assures that there always is a center, even if it was not set on the custom map object that should be used for the overview map.
=> Stabilize OverviewMap creation with custom map

package.json, src/data/store/Layers.js, test/index.html, test/spec/GeoExt/data/store/Layers.test.js
=> Use latest ol6

examples/features/grid-spatial-filter.js
The title says it all.
To test:
```
npx serve .
```
Then open http://localhost:3000/examples/features/grid-spatial-filter.html
=> Correct name of geometry attribute in spatial filter example

src/data/store/Layers.js
The `on` events were removed in newer versions of OpenLayers (they were present in 4.6.5 - https://openlayers.org/en/v4.6.5//apidoc/ol.Collection.html#on but not in the latest OL versions). 
In the latest mster version of GeoExt I get the following warnings. This pull request removes the symbols as I don't believe they are now required. 
```
[W] The class "GeoExt.data.store.Layers" depends on the external symbol "ol.Collection.prototype.on", which does not seem to exist.
[W] The class "GeoExt.data.store.Layers" depends on the external symbol "ol.layer.Layer.prototype.on", which does not seem to exist.
```
=> Fix warnings about "on" symbols in GeoExt.data.store.Layers

.github/workflows/on-push-master.yml, .github/workflows/on-tag.yml
The latest merges on master made this obvious:
https://github.com/geoext/geoext/actions/runs/3711233112/jobs/6291441920
This changes all workflows to use `ruby/setup-ruby@v1` instead of `actions/setup-ruby@v1`
This can most properly be tested once this PR is merged.
Please review @geoext/dev
=> Use a maintained GH action to setup ruby

.github/workflows/on-push-master.yml
#723 is working fine, but due to the non-optimal sed command we have duplicated `/` in the hosted examples:
This PR fixes that.
Please have another look, @geoext/dev (not urgent at all, since everything is working, it's just not nice and neat)
=> Cosmetic change to the sed action

examples/print/basic-mapfish.js, src/data/serializer/Vector.js
Without this the print example errors with
```
Uncaught DOMException: Failed to execute 'drawImage' on 'CanvasRenderingContext2D': The image argument is a canvas element with a width or height of 0.
at Function.encodeVectorStylePoint (https://geoext.github.io/geoext/master/src//data/serializer/Vector.js?_dc=1671108261136:408:45)
```
The used print service has been updated as well, and now the example is working locally again, thanks @dnlkoch.
I think in a follow-up we should remove the option to use `JSONP`, it seems as this is no longer supported. We have the switch `useJsonp` already in teh code, so this can be circumvented in userland easily.
Please review.
=> Fix issues when serializing OpenLayers icons for printing

src/data/store/WfsFeatures.js
This ensures that the inherited config property `passThroughFilter` is forced to `false` within `GeoExt.data.store.WfsFeatures`. This property only has an effect if a vector layer is bound, which is not possible for this type of store.
Furthermore this avoids possible unnecessary requests du to a filter change in the parent class `GeoExt.data.store.Features`, if `passThroughFilter` is set to true, see https://github.com/geoext/geoext/blob/master/src/data/store/Features.js#L189, which causes a reload due to https://github.com/geoext/geoext/blob/master/src/data/store/WfsFeatures.js#L371
=> Set 'passThroughFilter' to false in WfsFeatureStore

examples/component/map.js, examples/component/overviewMap.js, examples/filtered-heatmap/filtered-heatmap.js, examples/mapviewform/mapviewform.js, examples/modern-layerlist/modern-layerlist.js, examples/modern-map/modern-map.js, examples/popup/gx-popup.js, examples/state/stateful-map.js, examples/tree/panel.js, examples/tree/tree-legend-simple.js, package-lock.json, package.json, test/karma.conf.js, test/spec/GeoExt/data/MapfishPrintProvider.test.js, universal-app.md
This updates ol to version 8 and adapts the code correspondingly.
Some overviemap tests are failing chrome-headless when the `'--disable-gpu'` flag is activated so this option was outcommented.
=> Update ol to version 8

package.json
The tag docs folder doesn't currently match the package.json version (v7.0.0 and 7.0.0) stopping tagged releases documentation deploying automatically. See https://github.com/geoext/geoext/actions/runs/12280911563/job/34268488061
```
[INFO] clean up /home/runner/actions_github_pages_1733935398523/${GITHUB_REF##*/}
[INFO] chdir /home/runner/actions_github_pages_1733935398523/${GITHUB_REF##*/}
/usr/bin/git rm -r --ignore-unmatch *
[INFO] chdir /home/runner/actions_github_pages_1733935398523
[INFO] prepare publishing assets
[INFO] copy /home/runner/work/geoext/geoext/${GITHUB_REF##*/} to /home/runner/actions_github_pages_1733935398523/${GITHUB_REF##*/}
cp: no such file or directory: /home/runner/work/geoext/geoext/${GITHUB_REF##*/}/*
cp: no such file or directory: …
```
=> Add v prefix to docs output to match GitHub branch
